insert into labels (label, label_text) values ("citat","citation");
insert into labels (label, label_text) values ("auth_c","citation author");
insert into labels (label, label_text) values ("year","year");
insert into labels (label, label_text) values ("auth_all","all authors");
insert into labels (label, label_text) values ("abst","abstract");
insert into labels (label, label_text) values ("link","url or doi");
insert into labels (label, label_text) values ("title","title");
insert into labels (label, label_text) values ("journ","journal title");
insert into labels (label, label_text) values ("publ","publisher");
insert into labels (label, label_text) values ("vol","volume");
insert into labels (label, label_text) values ("issu","issue");
insert into labels (label, label_text) values ("page","page");
insert into labels (label, label_text) values ("study_s","study started");
insert into labels (label, label_text) values ("study_e","study ended");
insert into labels (label, label_text) values ("season","seasons");
insert into labels (label, label_text) values ("sp_m","main study species");
insert into labels (label, label_text) values ("sp_o","other study species");
insert into labels (label, label_text) values ("sp_b","other animals photographed");
insert into labels (label, label_text) values ("cam_b","camera used");
insert into labels (label, label_text) values ("dig","digital");
insert into labels (label, label_text) values ("pa_ac","camera trigger type");
insert into labels (label, label_text) values ("ir_wh","ir flash or white light");
insert into labels (label, label_text) values ("pair","paired cameras");
insert into labels (label, label_text) values ("camst_ma","sites per location - maximum");
insert into labels (label, label_text) values ("camst_mi","sites per location - minimum");
insert into labels (label, label_text) values ("camst","average camera sites per location");
insert into labels (label, label_text) values ("nig_st","nights per site");
insert into labels (label, label_text) values ("sites","total camera sites");
insert into labels (label, label_text) values ("areakm","study site area (km2)");
insert into labels (label, label_text) values ("no_seas","sampling seasons");
insert into labels (label, label_text) values ("placem","placement of cameras");
insert into labels (label, label_text) values ("spaci","spacing of camera stations");
insert into labels (label, label_text) values ("layout","layout of camera stations");
insert into labels (label, label_text) values ("mount","mounting of cameras");
insert into labels (label, label_text) values ("lure","bait or lure used");
insert into labels (label, label_text) values ("tot_n","total nights");
insert into labels (label, label_text) values ("tr_n","total trap-nights");
insert into labels (label, label_text) values ("targ_no","number of pictures of target species");
insert into labels (label, label_text) values ("tot_no","total number of pictures of animals");
insert into labels (label, label_text) values ("tot_im","total pictures taken including misfires");
insert into labels (label, label_text) values ("mis","number of misfires (blank photos)");
insert into labels (label, label_text) values ("ph_rate","photographic rate (nights/target photos)");
insert into labels (label, label_text) values ("analy_t","analysis type");
insert into labels (label, label_text) values ("analy_n","analysis notes");
insert into labels (label, label_text) values ("study_t","type of study");
insert into labels (label, label_text) values ("objecti","objectives of study");
insert into labels (label, label_text) values ("country","country");
insert into labels (label, label_text) values ("region","region");
insert into labels (label, label_text) values ("locat","location");
insert into labels (label, label_text) values ("locat_e","exact location (coordintates)");
insert into labels (label, label_text) values ("peerr","peer reviewed");
insert into labels (label, label_text) values ("email","corresponding author email");
insert into labels (label, label_text) values ("address","address given on study");
insert into labels (label, label_text) values ("quotes","quotes");
insert into labels (label, label_text) values ("notes","notes");
insert into labels (label, label_text) values ("term","terminology");

